# permissions for end users to view rainbondvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rainbondvolume-viewer-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondvolumes/status
  verbs:
  - get
