# permissions for end users to view rainbondclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rainbondcluster-viewer-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondclusters/status
  verbs:
  - get
