# permissions for end users to view rainbondpackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rainbondpackage-viewer-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondpackages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondpackages/status
  verbs:
  - get
