# permissions for end users to edit rainbondvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rainbondvolume-editor-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondvolumes/status
  verbs:
  - get
