# permissions for end users to edit rainbondpackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rainbondpackage-editor-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondpackages/status
  verbs:
  - get
