# permissions for end users to edit rainbondclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rainbondcluster-editor-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondclusters/status
  verbs:
  - get
