# permissions for end users to view rbdcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbdcomponent-viewer-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rbdcomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rbdcomponents/status
  verbs:
  - get
