
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondclusters/finalizers
  verbs:
  - update
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondpackages/finalizers
  verbs:
  - update
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondpackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondvolumes/finalizers
  verbs:
  - update
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rainbondvolumes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rbdcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rbdcomponents/finalizers
  verbs:
  - update
- apiGroups:
  - rainbond.io.rainbond.io
  resources:
  - rbdcomponents/status
  verbs:
  - get
  - patch
  - update
